version: '3.8'

services:

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - my-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 15s
      timeout: 10s
      retries: 5

  order:
    image: order:latest
    build:
      context: .
      dockerfile: Order.API/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - my-network
    environment:
      - RabbitMQ__HostName=host.docker.internal  # Use host.docker.internal to access the host

  user:
    image: user:latest
    build:
      context: .
      dockerfile: User.API/Dockerfile
    ports:
      - "8081:8080"
    networks:
      - my-network
    environment:
      - RabbitMQ__HostName=host.docker.internal  # Use host.docker.internal to access the host

  notification:
    image: notification:latest
    build:
      context: .
      dockerfile: NotificationService/Dockerfile
    ports:
      - "8082:8080"
    networks:
      - my-network
    environment:
      - RabbitMQ__HostName=host.docker.internal  # Use host.docker.internal to access the host
    depends_on:
     rabbitmq:
      condition: service_healthy

networks:
  my-network:
    driver: bridge
