version: '3.8'

services:

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"  # RabbitMQ default port
      - "15672:15672" # RabbitMQ management UI
    networks:
      - my-network

  order:
    image: order:latest
    build:
      context: .
      dockerfile: Order.API/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - my-network
    environment:
      - RabbitMQ__HostName=host.docker.internal  # Use host.docker.internal to access the host

  user:
    image: user:latest
    build:
      context: .
      dockerfile: User.API/Dockerfile
    ports:
      - "8081:8080"
    networks:
      - my-network
    environment:
      - RabbitMQ__HostName=host.docker.internal  # Use host.docker.internal to access the host

  notification:
    image: notification:latest
    build:
      context: .
      dockerfile: NotificationService/Dockerfile
    ports:
      - "8082:8080"
    networks:
      - my-network
    environment:
      - RabbitMQ__HostName=host.docker.internal  # Use host.docker.internal to access the host

networks:
  my-network:
    driver: bridge
